server:
  port: 8189
  servlet:
    context-path: /app/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: postgres
  jpa:
    show-sql: true
jwt:
  secret: 34klj42nb3e23445gghd32l54ure202gh43qrucvjrvtp854iobcdju54